skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sc_solana = "mBTgiF9KkZtxX5PpH3SnViBCAdkETz1yDbU1cdRNcc7"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-sbf"

[hooks]
